version: '2.1'
services:
  localstack:
    image: localstack/localstack
    ports:
      - '4566:4566'
    environment:
      - SERVICES=lambda,cloudformation,cloudwatch,sts,iam,apigateway
      - LAMBDA_EXECUTOR=docker
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
